# Generated by Django 4.2.9 on 2024-02-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0002_web_user_user_isactive_alter_web_user_user_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_user',
            old_name='user_pass',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='web_user',
            old_name='user_id',
            new_name='username',
        ),
    ]
