# Generated by Django 4.2.9 on 2024-02-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0005_college_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='profile_images/')),
                ('caption', models.CharField(max_length=255)),
            ],
        ),
    ]
