# Generated by Django 4.2.9 on 2024-02-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0007_alter_profileimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileimage',
            name='uname',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
