# Generated by Django 4.2.9 on 2024-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0008_profileimage_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_Data',
            fields=[
                ('erollmentno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=15)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('aadhar_no', models.CharField(max_length=15)),
                ('last_school_attended', models.CharField(max_length=15)),
                ('mother_tongue', models.CharField(max_length=15)),
                ('contact_no', models.CharField(max_length=15)),
                ('email_id', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=25)),
                ('religion', models.CharField(max_length=20)),
                ('shift', models.CharField(max_length=10)),
                ('loc_contact', models.CharField(max_length=15)),
                ('loc_address', models.CharField(max_length=150)),
                ('per_contact', models.CharField(max_length=15)),
                ('per_address', models.CharField(max_length=150)),
                ('admission_batch', models.CharField(max_length=12)),
                ('admission_mode', models.CharField(max_length=20)),
                ('admission_category', models.CharField(max_length=20)),
                ('admission_seat_type', models.CharField(max_length=20)),
            ],
        ),
    ]
