# Generated by Django 4.2.9 on 2024-02-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0010_alter_web_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='web_user',
            old_name='user_isactive',
            new_name='isactive',
        ),
        migrations.RemoveField(
            model_name='web_user',
            name='user_email',
        ),
    ]
