# Generated by Django 4.2.9 on 2024-03-01 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0011_rename_user_isactive_web_user_isactive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_user',
            name='isactive',
        ),
        migrations.AddField(
            model_name='web_user',
            name='user_isactive',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1),
        ),
    ]
