# Generated by Django 4.2.9 on 2024-03-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0012_remove_web_user_isactive_web_user_user_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_user',
            name='user_isactive',
        ),
    ]
