# Generated by Django 4.2.9 on 2024-03-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0013_remove_web_user_user_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileimage',
            old_name='image',
            new_name='path',
        ),
    ]
