# Generated by Django 4.2.9 on 2024-03-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0014_rename_image_profileimage_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_user',
            name='path',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
