# Generated by Django 4.2.9 on 2024-03-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0015_web_user_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_user',
            name='path',
        ),
        migrations.AddField(
            model_name='web_user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
