# Generated by Django 4.2.9 on 2024-03-14 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0016_remove_web_user_path_web_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_user',
            name='profile_picture',
        ),
    ]
