# Generated by Django 4.2.9 on 2024-03-14 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0017_remove_web_user_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileimage',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='uname',
        ),
        migrations.AddField(
            model_name='profileimage',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profileimage',
            name='path',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
