# Generated by Django 4.2.9 on 2024-03-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0018_remove_profileimage_caption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_user',
            name='path',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
