# Generated by Django 4.2.9 on 2024-03-14 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0019_web_user_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='web_user',
            name='path',
        ),
    ]
