# Generated by Django 4.2.9 on 2024-03-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0020_remove_web_user_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMaster',
            fields=[
                ('erollmentno', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=1)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('date_of_birth', models.DateField(auto_now_add=True)),
                ('date_of_admission', models.DateField(auto_now_add=True)),
                ('aadhar_no', models.CharField(max_length=15)),
                ('last_school_attended', models.CharField(max_length=300)),
                ('mother_tongue', models.CharField(max_length=20)),
                ('contact_no', models.CharField(max_length=15)),
                ('email_id', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=20)),
                ('caste', models.CharField(max_length=40)),
                ('religion', models.CharField(max_length=20)),
                ('shift', models.CharField(max_length=20)),
                ('local_contact', models.CharField(max_length=15)),
                ('local_address', models.CharField(max_length=150)),
                ('permanent_contact', models.CharField(max_length=15)),
                ('permanent_address', models.CharField(max_length=150)),
                ('admission_batch_year', models.CharField(max_length=12)),
                ('admission_mode', models.CharField(max_length=20)),
                ('admission_category', models.CharField(max_length=20)),
                ('admission_seat_type_alloted', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Student_Data',
        ),
    ]
