# Generated by Django 4.2.9 on 2024-03-24 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0021_studentmaster_delete_student_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('courseid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=300)),
                ('course_intake', models.IntegerField()),
                ('course_level', models.CharField(max_length=50)),
                ('course_core', models.CharField(max_length=50)),
                ('course_affiliation', models.CharField(max_length=100)),
                ('course_affiliation_fees', models.IntegerField()),
                ('course_affiliation_validfrom', models.DateField(max_length=100)),
                ('course_affiliation_validupto', models.DateField(max_length=100)),
                ('course_syllabi', models.FileField(default='images/syllabusnotfound.pdf', upload_to='images/')),
            ],
        ),
    ]
