# Generated by Django 4.2.9 on 2024-03-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0022_coursemaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemaster',
            name='course_affiliation_validfrom',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='coursemaster',
            name='course_affiliation_validupto',
            field=models.DateField(),
        ),
    ]
