# Generated by Django 4.2.9 on 2024-05-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0024_coursemaster_course_length_years_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursemaster',
            name='course_length_years',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coursemaster',
            name='course_medium',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='coursemaster',
            name='course_pattern',
            field=models.CharField(max_length=100),
        ),
    ]
