# Generated by Django 4.2.9 on 2024-06-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_home', '0025_alter_coursemaster_course_length_years_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='web_user',
            name='path',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
