# Generated by Django 4.2.9 on 2024-05-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePrimary',
            fields=[
                ('courseid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=300)),
                ('course_intake', models.IntegerField()),
                ('course_level', models.CharField(max_length=50)),
                ('course_core', models.CharField(max_length=50)),
                ('course_length_years', models.IntegerField()),
                ('course_pattern', models.CharField(max_length=100)),
                ('course_medium', models.CharField(max_length=50)),
                ('course_affiliation', models.CharField(max_length=100)),
                ('course_affiliation_fees', models.IntegerField()),
                ('course_affiliation_validfrom', models.DateField()),
                ('course_affiliation_validupto', models.DateField()),
                ('course_syllabi', models.FileField(default='images/syllabusnotfound.pdf', upload_to='images/')),
            ],
        ),
    ]
